In [189]:
# create subset uniformly
langtags = {'ha':'<ha>', 'yo':'<yo>'}
#{'am':'<am>', 'dz':'<dz>', 'ha':'<ha>', 'ig':'<ig>', 'kr':'<kr>', 'ma':'<ma>', 'pcm':'<pcm>', 'pt':'<pt>', 'sw':'<sw>', 'ts':'<ts>', 'twi':'<twi>', 'yo':'<yo>'}
#tags = [item for item in langtags.items()]

In [220]:
import pandas as pd
import os

class languages:
    def __init__(self, code, datapath):
        path = os.path.join(datapath, code+'_train.tsv')
        self.df = pd.read_csv(path, sep='\t')
        self.df = self.df.dropna()
        self.df['tag'] = code
        self.df['label'].value_counts()
        self.code = code
    
    def getmax(self):
        return df['label'].value_counts().max()
    
    def getmin(self):
        return df['label'].value_counts().min()
    
    def getsum(self):
        return df['label'].value_counts().sum()
    
    def sampleuniallclass(self, k):
        # uniformly sample across class and language
        return k.sample(self.nSamples, replace=True)
    
    def sampleuniall(self, nSamples=1):
        self.nSamples = nSamples
        sam = self.df.groupby('label').apply(self.sampleuniallclass)
        return sam
    
    def mergesampleall(self):
        return self.df

In [221]:
alllangsObjs = [languages(item,'./SubtaskA') for item in langtags]

In [222]:
uniformall = True
#mergeall = True
#uniformclass = False
if uniformall:
    # sample the data based on the class with the highest number of instances across languages
    minlabelsize = max([item.getmax() for item in alllangsObjs])
    classsample = [item.sampleuniall(nSamples = minlabelsize)  for item in alllangsObjs]
    sampleddata = pd.concat(classsample)
elif mergeall:
    # concatenate all the data without any extra sampling
    classsample = [item.mergesampleall() for item in alllangsObjs]
    sampleddata = pd.concat(classsample)

In [224]:
sampleddata.head()

                           ID  \
label
negative 1275  ha_train_01276
         1634  ha_train_01635
         1286  ha_train_01287
         3860  ha_train_03861
         2633  ha_train_02634

                                                           tweet     label tag
label
negative 1275  @user @user Tsakani ga Allah Gomnoninmu sunji ...  negative  ha
         1634  @user Karyan banza da na wopi. Duk mun gane in...  negative  ha
         1286  @user dama munafukaine, sungwammaci Israela ak...  negative  ha
         3860  @user @user Ku gama Zalincinku idan Allah ya t...  negative  ha
         2633                   @user Meh karya Dan Wuta balbalüò´  negative  ha

In [225]:
sampleddata.tail()

                           ID  \
label
positive 6572  yo_train_06573
         6053  yo_train_06054
         6835  yo_train_06836
         5470  yo_train_05471
         6437  yo_train_06438

                                                           tweet     label tag
label
positive 6572  RT @user: K·ªçÃÅj·ªçÃÅd√° 10062! ·ªåj·ªçÃÅ d√°, ·ªçj·ªçÃÅ sunw·ªçÃÄ...  positive  yo
         6053  .@user omo ti iya bi to fi oja pon. Mo taka os...  positive  yo
         6835  üì∏ü§∞ü§∞üçå Eba wa gbe igba ope o, eba wa jo, eba wa ...  positive  yo
         5470  üì≥@user @user @user @user ·∫∏ wo √†w√≤k·ªçÃÅ·π£e rere!üì≥ ...  positive  yo
         6437  Mo k√≠ gbogbo M√πs√πl√πm√≠ k√∫ ·ªçd√∫n o. ·∫∏ k√∫ √†gb√†t√°n ...  positive  yo